#!/bin/sh
workspaces() {

ws1="1"
ws2="2"
ws3="3"
ws4="4"
ws5="5"
ws6="6"

# check if Occupied
o1=$(bspc query -D -d .occupied --names | grep "$ws1" )
o2=$(bspc query -D -d .occupied --names | grep "$ws2" )
o3=$(bspc query -D -d .occupied --names | grep "$ws3" )
o4=$(bspc query -D -d .occupied --names | grep "$ws4" )
o5=$(bspc query -D -d .occupied --names | grep "$ws5" )
o6=$(bspc query -D -d .occupied --names | grep "$ws6" )

# check if Focused
f1=$(bspc query -D -d focused --names | grep "$ws1" )
f2=$(bspc query -D -d focused --names | grep "$ws2" )
f3=$(bspc query -D -d focused --names | grep "$ws3" )
f4=$(bspc query -D -d focused --names | grep "$ws4" )
f5=$(bspc query -D -d focused --names | grep "$ws5" )
f6=$(bspc query -D -d focused --names | grep "$ws6" )

cat << EOF | xargs
(box :class '"workspaces"' :spacing 10 :orientation '"h"' :valign '"center"' :halign '"center"' :space-evenly '"false"'
  (eventbox :class '"event-listener isfocussed$f1 isoccupied$o1"' :onclick '"bspc desktop -f $ws1"' (label :class '"square-content"' :text '"1"'))
  (eventbox :class '"event-listener isfocussed$f2 isoccupied$o2"' :onclick '"bspc desktop -f $ws2"' (label :class '"square-content"' :text '"2"'))
  (eventbox :class '"event-listener isfocussed$f3 isoccupied$o3"' :onclick '"bspc desktop -f $ws3"' (label :class '"square-content"' :text '"3"'))
  (eventbox :class '"event-listener isfocussed$f4 isoccupied$o4"' :onclick '"bspc desktop -f $ws4"' (label :class '"square-content"' :text '"4"'))
  (eventbox :class '"event-listener isfocussed$f5 isoccupied$o5"' :onclick '"bspc desktop -f $ws5"' (label :class '"square-content"' :text '"5"'))
  (eventbox :class '"event-listener isfocussed$f6 isoccupied$o6"' :onclick '"bspc desktop -f $ws6"' (label :class '"square-content"' :text '"6"'))
)
EOF

}
workspaces
bspc subscribe all | while read -r _ ; do
workspaces
done
