#!/bin/sh

# requirements: dmenu, awk

# add all folders you want to be able to mount partitions to here
MOUNT_POINTS="$HOME/USB
/E
/USB
Quit"

# get all mountable partitions
MOUNT_TARGETS=$(lsblk --noheadings --paths --raw | grep '^.*part\ $' | awk '{ print $1 " (" $4 ")" }')

# get user's partition selection + check if selection was cancelled
TARGET=$(printf "%s\nQuit\n" "$MOUNT_TARGETS" | dmenu -i -l 20 -p "Partition to mount:" | awk ' {print $1 }')
[ -z "$TARGET" ] || [ "$TARGET" = "Quit" ] && exit 0

# get user's mounting location selection and check if selection was cancelled + if folder exists
TARGET_DIR=$(echo "$MOUNT_POINTS" | dmenu -i -l 20 -p "Mount ""$TARGET"" at:" | awk ' {print $1 }')
[ -z "$TARGET_DIR" ] || [ "$TARGET_DIR" = "Quit" ] || [ ! -d "$TARGET_DIR" ]&& exit 0

# mount target partition to target directory
sudo mount "$TARGET" "$TARGET_DIR"

