#!/bin/bash

# requirements: jq, dmenu, sqlite3

notify() { echo "$@"; }
command -V notify-send 1>/dev/null 2>&1 && notify() { notify-send "$@"; }

[ -z "$BROWSER" ] && {
  notify "Please set BROWSER variable"
  exit 1
}

get_bookmarks_chromium() {
  BM_FILE="$HOME/.config/chromium/Default/Bookmarks"
  jq '.. | objects | select(.type == "url") | "\(.name),,,\(.url)"' \
    --raw-output "$BM_FILE"
}

get_bookmarks_firefox() {
  BM_FILE="$HOME/.mozilla/firefox/88fot2o2.default-release/places.sqlite"
  sqlite3 --separator ",,," \
    "file:$BM_FILE?immutable=1" \
    "SELECT mb.title,mp.url from moz_bookmarks mb JOIN moz_places mp on mb.fk=mp.id;"
}

case "$BROWSER" in
"chromium") get_bookmarks() { get_bookmarks_chromium; } ;;
"firefox") get_bookmarks() { get_bookmarks_firefox; } ;;
*)
  notify "Unsupported browser"
  exit 1
  ;;
esac

declare -A bmdict
while IFS=',' read -r key value; do
  [ -n "$key" ] && bmdict["$key"]="$value"
done < <(get_bookmarks)

# get selection + check if selection was cancelled
KEY=$(printf "%s\n" "${!bmdict[@]}" | dmenu -i -c -l 20 -p "Open bookmark:")
[ -z "$KEY" ] && exit 0

# open selected bookmark
"$BROWSER" --new-window "${bmdict[$KEY]//,,/}" &
disown
