#!/bin/sh

# requirements: dmenu, awk

# select network device
NET_DEVICE=$(find /sys/class/net/* | sed 's|^.*/||g' | dmenu -i -l 20 -p "Select drive:")

# check if selection was cancelled
[ -z "$NET_DEVICE" ] || [ "$NET_DEVICE" = "Quit" ] && exit 0

# get desired action
ACTIONS="Change state [up/down]
Change noarp flag [arp on/arp off]
Change multicast flag [multicast on/multicast off]
Change dynamic flag [dynamic on/dynamic off]
Quit"

ACTION_CHOICE=$(echo "$ACTIONS" | dmenu -i -l 20 -p "Desired action:" | awk '{print $2}')
[ -z "$ACTION_CHOICE" ] || [ "$ACTION_CHOICE" = "Quit" ] && exit 0

# special case, state is not a keyword in the command and uses different arguments
if [ "$ACTION_CHOICE" = "state" ]; then
  OPERATION=$(printf "up\ndown\nQuit" | dmenu -i -l 20 -p "Desired operation:")
  # check if selection was cancelled
  [ -z "$OPERATION" ] || [ "$OPERATION" = "Quit" ] && exit 0
  sudo ip link set "$NET_DEVICE" "$OPERATION" && exit 0
fi

OPERATION=$(printf "on\noff\nQuit" | dmenu -i -l 20 -p "Desired operation:")
# check if selection was cancelled
[ -z "$OPERATION" ] || [ "$OPERATION" = "Quit" ] && exit 0

sudo ip link set "$NET_DEVICE" "$ACTION_CHOICE" "$OPERATION" && exit 0

