#!/bin/sh

# requirements: dmenu, awk

# get desired action
ACTIONS="Shutdown
Reboot
Quit"

# get user selection (in lower-case, this makes it easier to execute the appropriate command later)
ACTION_CHOICE=$(printf "%s" "$ACTIONS" | dmenu -i -l 20 -p "Desired operation:" | awk '{ print tolower($1) }')

# if action choice is none or quit, immediately exit script
[ -z "$ACTION_CHOICE" ] || [ "$ACTION_CHOICE" = "quit" ] && exit 0

# confirm user selection
CONFIRMATION=$(printf "Yes\nNo"  | dmenu -i -l 20 -p "Are you sure you want to $ACTION_CHOICE?")
[ "$CONFIRMATION" != "Yes" ] && exit 0

sudo "$ACTION_CHOICE" now
