vim.cmd('set encoding=utf-8')
vim.cmd('set hidden') -- allows switching buffers without saving them
vim.cmd('set relativenumber')
vim.cmd('set termguicolors')
vim.cmd('set showmatch')
vim.cmd('set nohlsearch')
vim.cmd('set tabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('set expandtab')
vim.cmd('set nu')
vim.cmd('set noswapfile')
vim.cmd('set nobackup')
vim.cmd('set incsearch')
vim.cmd('set ignorecase')
vim.cmd('set cursorline')
vim.cmd('set scrolloff=8')
vim.cmd('set noshowmode')
vim.cmd('set clipboard+=unnamedplus')
vim.cmd('set nowrap')
vim.cmd('set showtabline=2')
vim.cmd('set mouse=a')
vim.cmd('set autoindent')
-- vim.cmd('set formatoptions-=cro')
vim.cmd('colorscheme gruvbox')
vim.cmd('set bg=dark')

vim.cmd('autocmd BufRead,BufNew,BufEnter *.* set formatoptions-=cro')
