#!/bin/sh

# requirements: pass, dmenu, find
# Change this variable to te (absolute) path of your password-store
PASS_DIR="$HOME/.password-store/"

cd $PASS_DIR && find -name "*.gpg" | sed -e 's|\./||' -e 's|\.gpg$||' | dmenu | xargs pass -c

