#!/usr/bin/env bash

# lock command taken from: https://github.com/janleigh/dotfiles/blob/master/bin/lck
#
lock_screen() {
i3lock -n -c 00000000 -t -e --pass-media-keys --pass-power-keys --pass-volume-keys --indicator --force-clock \
  --ignore-empty --radius 52 --modif-size=9 --modif-pos="w/2:h/2-15" \
  \
  --time-str="%H:%M" \
  --time-pos="w/2:h/4" \
  --time-color=c5c8c9 \
  --time-size=120 \
  --time-font="DM Sans" \
  \
  --date-str="%A, %B %d" \
  --date-pos="w/2:h/4+40" \
  --date-color=c5c8c9 \
  --date-size=35 \
  --date-font="DM Sans" \
  \
  --verif-text="" \
  --verif-color=7ba5dd \
  --verif-size=10 \
  --verif-font="Sarasa Mono CL Nerd Font" \
  \
  --wrong-text="" \
  --wrong-color=ee6a70 \
  --wrong-size=10 \
  --wrong-font="Sarasa Mono CL Nerd Font" \
  \
  --greeter-text="" \
  --greeter-color=96d6b0 \
  --greeter-size=60 \
  --greeter-font="Sarasa Mono CL Nerd Font" \
  --greeter-pos="w/2:h/2+285" \
  \
  --ring-color=00000000 \
  --ringver-color=96D6B0 \
  --ringwrong-color=ee6a70 \
  --ring-width=5 \
  \
  --insidever-color=079A8C02 \
  --insidewrong-color=079A8C02 \
  --inside-color=079A8C02 \
  --ind-pos="w/2:h-130" \
  \
  --noinput-text="" \
  \
  --line-uses-inside --keyhl-color=cb92f2 --bshl-color=ee6a70 --separator-color=00000000 \
  \
  --pointer=default
}

trap revert HUP INT TERM
xset dpms 10 10 10
lock_screen
# reset dpms
xset dpms 600 600 600
