#!/bin/bash

# brightness control script
# script takes a single argument (inc/dec) and modifies the backlight level
# accordingly.

[[ "$#" -ne 1 ]] && echo "Please supply a flag [i/d]" && exit 1
! hash brightnessctl  &>/dev/null && notify-send -u low "brightnessctl not installed" && exit 1

curr_brightness=$(brightnessctl -m | cut -d',' -f4)
curr_brightness=${curr_brightness//\%/}
delta=5

[[ "$1" = "-i" ]] && brightnessctl s "$delta"%+ && notify-send "Brightness increased ($((curr_brightness+delta))%)" && exit 0

# decreasing brightness requires some more thought as decreasing "below" 0%
# forces the system to go into sleep mode, preventing further keyboard inputs
# until the lid is closed and opened again, for inotify-sendtance to increase the
# brightness once more.
[[ "$1" = "-d" ]] && [[ $((curr_brightness-delta)) -gt 0 ]] && brightnessctl s "$delta"%- && notify-send "Brightness decreased ($((curr_brightness-delta))%)" && exit 0

notify-send -u low "Warning: already at min brightness!" && exit 1
