#!/bin/bash

is_visible() {
  eww windows | grep bar | grep '\*'
}

root_id=$(xdo id -n root)

if [[ $(is_visible) ]]; then
  eww close bar
  # eww bar could be anchored on any side of the monitor. This ensures that
  # wherever it is placed the padding is reset appropriately. There is likely a
  # cleaner way to do this than simply brute-forcing, but it works, so...
  bspc config top_padding 0
  bspc config bottom_padding 0
  bspc config left_padding 0
  bspc config right_padding 0
else
  eww open bar
  xdo above -t "$root_id" -n eww-bar
fi
