name: CI

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v19

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}

      - name: Unlock repository secrets
        run: |
          nix profile install nixpkgs#git-crypt
          git-crypt unlock

      - name: Check code format
        run: nix fmt

      - name: Check for dead code
        run: |
          nix profile install nixpkgs#deadnix
          deadnix --fail --no-lambda-pattern-names

      - name: Check nix flake
        run: nix flake check
