name: Format

on: [push, pull_request]

jobs:
  format-nvim-config:
    name: Stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check nvim/.config/nvim
  format-readme:
    name: Markdown-Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Markdown-Lint
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: './readme.md'
